// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC83h_iF91OiE8GR1ke-DiFonF1nr8iVjg',
    appId: '1:46779380086:web:c862149c34842efd0e0a57',
    messagingSenderId: '46779380086',
    projectId: 'paysatu-c663e',
    authDomain: 'paysatu-c663e.firebaseapp.com',
    storageBucket: 'paysatu-c663e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHHVpTQ69veVvd8ZB0jWmhldrclWATm3o',
    appId: '1:46779380086:android:84e3c529dd83e8c40e0a57',
    messagingSenderId: '46779380086',
    projectId: 'paysatu-c663e',
    storageBucket: 'paysatu-c663e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHHCwt6d2odXEju52rPQZPeigUNJvt-4A',
    appId: '1:46779380086:ios:7c02e94ab73365f00e0a57',
    messagingSenderId: '46779380086',
    projectId: 'paysatu-c663e',
    storageBucket: 'paysatu-c663e.appspot.com',
    iosBundleId: 'com.example.paysatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHHCwt6d2odXEju52rPQZPeigUNJvt-4A',
    appId: '1:46779380086:ios:7c02e94ab73365f00e0a57',
    messagingSenderId: '46779380086',
    projectId: 'paysatu-c663e',
    storageBucket: 'paysatu-c663e.appspot.com',
    iosBundleId: 'com.example.paysatu',
  );
}
